<x-layout>
    <x-slot:title>Analytics - CodeQuest</x-slot:title>

    <div class="container py-5">
        <h1 class="mb-4">📈 Platform Analytics</h1>
        <p class="text-muted mb-4">Explore growth and engagement trends generated by the analytics controller.</p>

        <div class="row g-3 mb-5">
            @forelse($growthMetrics as $metric)
                <div class="col-md-4">
                    <div class="card shadow-sm border-0 h-100">
                        <div class="card-body">
                            <span class="text-muted text-uppercase small">{{ $metric->metric ?? 'Metric' }}</span>
                            <h3 class="mt-2">{{ number_format($metric->current_value ?? 0) }}</h3>
                            @php $change = $metric->change_percentage ?? null; @endphp
                            <div class="d-flex align-items-center gap-2">
                                @if(!is_null($change))
                                    <span class="badge {{ $change >= 0 ? 'bg-success' : 'bg-danger' }}">
                                        {{ $change >= 0 ? '+' : '' }}{{ number_format($change, 1) }}%
                                    </span>
                                    <small class="text-muted">vs previous period</small>
                                @else
                                    <span class="badge bg-secondary">—</span>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            @empty
                <div class="col-12">
                    <div class="alert alert-light border">No growth metrics available.</div>
                </div>
            @endforelse
        </div>

        <div class="card shadow-sm border-0 mb-5">
            <div class="card-header bg-primary text-white">Weekly Trends</div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-striped mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>Week Starting</th>
                                <th class="text-end">Submissions</th>
                                <th class="text-end">Active Users</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($weeklyTrends as $trend)
                                <tr>
                                    <td>{{ $trend->week_start }}</td>
                                    <td class="text-end">{{ number_format($trend->submission_count ?? 0) }}</td>
                                    <td class="text-end">{{ number_format($trend->active_users ?? 0) }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" class="text-center text-muted">No weekly trend data available.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="card shadow-sm border-0">
            <div class="card-header bg-secondary text-white">Daily Activity</div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>Date</th>
                                <th class="text-end">Solved</th>
                                <th class="text-end">New Users</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($dailyActivity as $day)
                                <tr>
                                    <td>{{ $day->formatted_date ?? $day->activity_date }}</td>
                                    <td class="text-end">{{ number_format($day->solved_count ?? 0) }}</td>
                                    <td class="text-end">{{ number_format($day->new_users ?? 0) }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" class="text-center text-muted">No day-by-day activity yet.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-layout>
