<x-layout>
    <x-slot:title>Leaderboard - CodeQuest</x-slot:title>

    <div class="container py-5">
        <div class="d-flex flex-wrap align-items-center justify-content-between mb-4">
            <div>
                <h1 class="mb-1">🏆 Leaderboard</h1>
                <p class="text-muted mb-0">Ranking generated by the leaderboard controller using cumulative ratings and solves.</p>
            </div>
            <form method="GET" action="{{ route('advanced.leaderboard') }}" class="d-flex align-items-center gap-2">
                <label for="sort" class="text-muted small mb-0">Order by</label>
                <select id="sort" name="sort" class="form-select form-select-sm" onchange="this.form.submit()">
                    @php $currentSort = request('sort', 'rating'); @endphp
                    <option value="rating" {{ $currentSort === 'rating' ? 'selected' : '' }}>Rating</option>
                    <option value="solved" {{ $currentSort === 'solved' ? 'selected' : '' }}>Solved Problems</option>
                    <option value="streak" {{ $currentSort === 'streak' ? 'selected' : '' }}>Streak</option>
                </select>
            </form>
        </div>

        <div class="card border-0 shadow-sm">
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>#</th>
                                <th>User</th>
                                <th>Handle</th>
                                <th class="text-end">Rating</th>
                                <th class="text-end">Solved</th>
                                <th class="text-end">Longest Streak</th>
                                <th class="text-end">Last Active</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($leaderboard as $index => $user)
                                <tr>
                                    <td>{{ $user->rank ?? $index + 1 }}</td>
                                    <td>{{ $user->name ?? $user->user_name ?? 'Unknown' }}</td>
                                    <td>{{ $user->cf_handle ?? '—' }}</td>
                                    <td class="text-end"><span class="badge bg-primary">{{ $user->cf_rating ?? $user->rating ?? '—' }}</span></td>
                                    <td class="text-end">{{ number_format($user->total_solved ?? $user->solved_count ?? 0) }}</td>
                                    <td class="text-end">{{ number_format($user->longest_streak ?? 0) }}</td>
                                    <td class="text-end">{{ optional($user->last_activity_at ?? null, fn ($date) => \Carbon\Carbon::parse($date)->diffForHumans()) ?? '—' }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-center text-muted">No leaderboard entries available.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-layout>
