<?php if (isset($component)) { $__componentOriginal23a33f287873b564aaf305a1526eada4 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal23a33f287873b564aaf305a1526eada4 = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.layout','data' => []] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('title', null, []); ?> Analytics - CodeQuest <?php $__env->endSlot(); ?>

    <div class="container py-5">
        <h1 class="mb-4">📈 Platform Analytics</h1>
        <p class="text-muted mb-4">Explore growth and engagement trends generated by the analytics controller.</p>

        <div class="row g-3 mb-5">
            <?php $__empty_1 = true; $__currentLoopData = $growthMetrics; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $metric): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                <div class="col-md-4">
                    <div class="card shadow-sm border-0 h-100">
                        <div class="card-body">
                            <span class="text-muted text-uppercase small"><?php echo e($metric->metric ?? 'Metric'); ?></span>
                            <h3 class="mt-2"><?php echo e(number_format($metric->current_value ?? 0)); ?></h3>
                            <?php $change = $metric->change_percentage ?? null; ?>
                            <div class="d-flex align-items-center gap-2">
                                <?php if(!is_null($change)): ?>
                                    <span class="badge <?php echo e($change >= 0 ? 'bg-success' : 'bg-danger'); ?>">
                                        <?php echo e($change >= 0 ? '+' : ''); ?><?php echo e(number_format($change, 1)); ?>%
                                    </span>
                                    <small class="text-muted">vs previous period</small>
                                <?php else: ?>
                                    <span class="badge bg-secondary">—</span>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                <div class="col-12">
                    <div class="alert alert-light border">No growth metrics available.</div>
                </div>
            <?php endif; ?>
        </div>

        <div class="card shadow-sm border-0 mb-5">
            <div class="card-header bg-primary text-white">Weekly Trends</div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-striped mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>Week Starting</th>
                                <th class="text-end">Submissions</th>
                                <th class="text-end">Active Users</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $__empty_1 = true; $__currentLoopData = $weeklyTrends; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $trend): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                                <tr>
                                    <td><?php echo e($trend->week_start); ?></td>
                                    <td class="text-end"><?php echo e(number_format($trend->submission_count ?? 0)); ?></td>
                                    <td class="text-end"><?php echo e(number_format($trend->active_users ?? 0)); ?></td>
                                </tr>
                            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                                <tr>
                                    <td colspan="3" class="text-center text-muted">No weekly trend data available.</td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="card shadow-sm border-0">
            <div class="card-header bg-secondary text-white">Daily Activity</div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>Date</th>
                                <th class="text-end">Solved</th>
                                <th class="text-end">New Users</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $__empty_1 = true; $__currentLoopData = $dailyActivity; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $day): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                                <tr>
                                    <td><?php echo e($day->formatted_date ?? $day->activity_date); ?></td>
                                    <td class="text-end"><?php echo e(number_format($day->solved_count ?? 0)); ?></td>
                                    <td class="text-end"><?php echo e(number_format($day->new_users ?? 0)); ?></td>
                                </tr>
                            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                                <tr>
                                    <td colspan="3" class="text-center text-muted">No day-by-day activity yet.</td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal23a33f287873b564aaf305a1526eada4)): ?>
<?php $attributes = $__attributesOriginal23a33f287873b564aaf305a1526eada4; ?>
<?php unset($__attributesOriginal23a33f287873b564aaf305a1526eada4); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal23a33f287873b564aaf305a1526eada4)): ?>
<?php $component = $__componentOriginal23a33f287873b564aaf305a1526eada4; ?>
<?php unset($__componentOriginal23a33f287873b564aaf305a1526eada4); ?>
<?php endif; ?>
<?php /**PATH C:\xampp\htdocs\CodeQuest\resources\views/advanced/analytics.blade.php ENDPATH**/ ?>